"""add user_id to reply table

Revision ID: 9d30f93cc26d
Revises: 388bd84da6d4
Create Date: 2024-11-26 22:31:35.911221

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9d30f93cc26d'
down_revision: Union[str, None] = '388bd84da6d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reply', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'reply', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'reply', type_='foreignkey')
    op.drop_column('reply', 'user_id')
    # ### end Alembic commands ###
